name: Print Hello

on:
  push:
    branches:
      - main

jobs:
  print-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print hello
        run: echo "hello"
